version: "3.6"
services:
  postgres:
    image: postgres:14.1
    container_name: postgres${DOCKER_ID}
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - PG_RANDOM_ID=${PG_RANDOM_ID}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SOLANA_READER_DATABASE=${POSTGRES_SOLANA_READER_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - debridge-node-network
  solana-grpc-service:
    image: debridgefinance/debridge-solana-events-reader-grpc-server:v0.5.0-dev.0-lima
    hostname: grpc-service
    networks:
      - debridge-node-network
    ports:
      # Right part depend on DEBRIDGE_EVENTS_GRPC_ADDRESS env variable
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      - RUST_LOG=${RUST_LOG}
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SOLANA_READER_DATABASE=${POSTGRES_SOLANA_READER_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBRIDGE_SETTINGS_PROGRAM_PUBKEY=${DEBRIDGE_SETTINGS_PROGRAM_PUBKEY}
      - DEBRIDGE_PROGRAM_PUBKEY=${DEBRIDGE_PROGRAM_PUBKEY}
      - DEBRIDGE_EVENTS_SOLANA_CLUSTER=${DEBRIDGE_EVENTS_SOLANA_CLUSTER}
      - DEBRIDGE_EVENTS_SOLANA_WEBSOCKET_CLUSTER=${DEBRIDGE_EVENTS_SOLANA_WEBSOCKET_CLUSTER}
      - DEBRIDGE_EVENTS_CACHE_PATH=${DEBRIDGE_EVENTS_CACHE_PATH}
      - DEBRIDGE_EVENTS_RESYNC_SIGNATURES_CHUNK_SIZE=${DEBRIDGE_EVENTS_RESYNC_SIGNATURES_CHUNK_SIZE}
      - DEBRIDGE_EVENTS_COMMITMENT_LEVEL=${DEBRIDGE_EVENTS_COMMITMENT_LEVEL}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_SEND=${DEBRIDGE_EVENTS_IS_INTERCEPT_SEND}
      - DEBRIDGE_EVENTS_IS_EXTERNAL_CALL_NEEDED=${DEBRIDGE_EVENTS_IS_EXTERNAL_CALL_NEEDED}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_CLAIM=${DEBRIDGE_EVENTS_IS_INTERCEPT_CLAIM}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_BRIDGE_CREATING=${DEBRIDGE_EVENTS_IS_INTERCEPT_BRIDGE_CREATING}
      - DEBRIDGE_EVENTS_PSQL=${DEBRIDGE_EVENTS_PSQL}
      - DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS=${DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS}
      - DEBRIDGE_EVENTS_DB_REQUERY_TIMEOUT_IN_SEC=${DEBRIDGE_EVENTS_DB_REQUERY_TIMEOUT_IN_SEC}
      - DEBRIDGE_EVENTS_HEARTBEAT_TIMEOUT_IN_SEC=${DEBRIDGE_EVENTS_HEARTBEAT_TIMEOUT_IN_SEC}
  solana-events-reader:
    image: debridgefinance/debridge-solana-events-reader:v0.5.0-dev.0-lima
    hostname: events-reader
    networks:
     - debridge-node-network
    depends_on:
      - postgres
    environment:
      - RUST_LOG=${RUST_LOG}
      - ENVIRONMENT=${ENVIRONMENT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SOLANA_READER_DATABASE=${POSTGRES_SOLANA_READER_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBRIDGE_SETTINGS_PROGRAM_PUBKEY=${DEBRIDGE_SETTINGS_PROGRAM_PUBKEY}
      - DEBRIDGE_PROGRAM_PUBKEY=${DEBRIDGE_PROGRAM_PUBKEY}
      - DEBRIDGE_EVENTS_SOLANA_CLUSTER=${DEBRIDGE_EVENTS_SOLANA_CLUSTER}
      - DEBRIDGE_EVENTS_SOLANA_WEBSOCKET_CLUSTER=${DEBRIDGE_EVENTS_SOLANA_WEBSOCKET_CLUSTER}
      - DEBRIDGE_EVENTS_CACHE_PATH=${DEBRIDGE_EVENTS_CACHE_PATH}
      - DEBRIDGE_EVENTS_RESYNC_SIGNATURES_CHUNK_SIZE=${DEBRIDGE_EVENTS_RESYNC_SIGNATURES_CHUNK_SIZE}
      - DEBRIDGE_EVENTS_COMMITMENT_LEVEL=${DEBRIDGE_EVENTS_COMMITMENT_LEVEL}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_SEND=${DEBRIDGE_EVENTS_IS_INTERCEPT_SEND}
      - DEBRIDGE_EVENTS_IS_EXTERNAL_CALL_NEEDED=${DEBRIDGE_EVENTS_IS_EXTERNAL_CALL_NEEDED}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_CLAIM=${DEBRIDGE_EVENTS_IS_INTERCEPT_CLAIM}
      - DEBRIDGE_EVENTS_IS_INTERCEPT_BRIDGE_CREATING=${DEBRIDGE_EVENTS_IS_INTERCEPT_BRIDGE_CREATING}
      - DEBRIDGE_EVENTS_PSQL=${DEBRIDGE_EVENTS_PSQL}
      - DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS=${DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS}
      - DEBRIDGE_EVENTS_DB_REQUERY_TIMEOUT_IN_SEC=${DEBRIDGE_EVENTS_DB_REQUERY_TIMEOUT_IN_SEC}
      - DEBRIDGE_EVENTS_HEARTBEAT_TIMEOUT_IN_SEC=${DEBRIDGE_EVENTS_HEARTBEAT_TIMEOUT_IN_SEC}
    volumes:
      - './.cache/events/:/var/opt/.debridge_events_cache'

  debridge-node:
    image: debridgefinance/debridge-node:2.5.7@sha256:bf73890a589539b174b72ac3dd711b40bb1ee9fe81654f079465caa907961d60
    container_name: debridge-node${DOCKER_ID}
    restart: unless-stopped
    secrets:
      - source: keystore
        target: /app/keystore.json
      - source: bundlr_wallet
        target: /app/bundlr_wallet.json
    volumes:
      - ./stats/debridge-node:/app/stats
      - ./config:/app/dist/config
    environment:
      - DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS=${DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS}
      - SOLANA_GRPC_SERVICE_URL=${SOLANA_GRPC_SERVICE_URL}
      - PORT=${DEBRIDGE_NODE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - API_BASE_URL=${API_BASE_URL}
      - API_LOGIN=${API_LOGIN}
      - API_PASSWORD=${API_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - NODE_OPTIONS=${DEBRIDGE_NODE_NODE_OPTIONS}
      - THROTTLER_TTL=${THROTTLER_TTL}
      - THROTTLER_LIMIT=${THROTTLER_LIMIT}
      - WEB3_TIMEOUT=${WEB3_TIMEOUT}
      - ENABLE_DATAFIX=${ENABLE_DATAFIX}
      - BUNDLR_NODE=${BUNDLR_NODE}
    depends_on:
      - postgres
      - solana-events-reader
      - solana-grpc-service
    networks:
      - debridge-node-network
networks:
  debridge-node-network:
    name: debridge-node-network
secrets:
  keystore:
    file: ./secrets/keystore.json
  bundlr_wallet:
    file: ./secrets/bundlr_wallet.json